#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d  󰨞 󰖟  󰎙  󰉋   
# bspc monitor -d 1 2 3 4 5 6 7

# MONITORES
SCREEN=$(xrandr | grep " connected " | wc -l)

if [[ $SCREEN -eq 1 ]]; then
	$HOME/.screenlayout/resolucion.sh
	bspc monitor eDP-1 -d 1 2 3 4 5
	$HOME/.config/polybar/launch.sh
fi

if [[ $SCREEN -eq 2 ]]; then
	$HOME/.screenlayout/resolucion-2p.sh
	bspc monitor 'eDP-1' -d 1 2 3 4 5
	bspc monitor 'HDMI-1' -d 6 7
	$HOME/.config/polybar/launch2.sh
fi

bspc config border_width         1
bspc config window_gap          12
# bspc config top_padding	         0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a dbeaver state=floating

# export _JAVA_AWT_WM_NONREPARENTING=1
wmname	LG3D
