[font]
size = 8.5

builtin_box_drawing = true

# normal = { family = "JetBrainsMono", style = "Bold" }
normal = { family = "JetBrainsMono", style = "Bold" }
# bold = { family = "JetBrainsMono NF", style = "Bold" }
# italic = { family = "JetBrainsMono NF", style = "Italic" }
# bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }
